defaults:
  - _self_
  - model: node
  - dataset: bouncingball_10000samples_75steps
  - training: default

hydra:
  output_subdir: null
  run:
    dir: .

# Random seed of the run
seed: 125125125

# Experiment folder naming
expname: ${seed}seed_${dataset.dataset}_${training.num_steps}iterations_${model.model_type}
model_path: ""
checkpt: ""

# For training, overrideable by cmd
train: true
resume: false

# Whether to save reconstructions to disk
save_files: true